"""empty message

Revision ID: 62d1b20f2e89
Revises: 
Create Date: 2021-03-31 16:13:21.522508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62d1b20f2e89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('common_names', postgresql.ARRAY(sa.String(length=256)), nullable=True),
    sa.Column('genus_species', sa.String(length=256), nullable=True),
    sa.Column('family', sa.String(length=256), nullable=True),
    sa.Column('native_range', sa.String(length=1000), nullable=True),
    sa.Column('temp_range', sa.String(length=10), nullable=True),
    sa.Column('light', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=1000), nullable=True),
    sa.Column('water_when', sa.String(length=1000), nullable=True),
    sa.Column('fertilization', sa.String(length=1000), nullable=True),
    sa.Column('pests', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('propogation_methods', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('toxic_to_pets', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_pic', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('watered', sa.Boolean(), nullable=False),
    sa.Column('fertilized', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('progress_pic', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('plants')
    op.drop_table('images')
    op.drop_table('users')
    op.drop_table('profiles')
    # ### end Alembic commands ###
